language: csharp
solution: Natasha.sln
dist: xenial
dotnet: 3.0.100
dotnet: 2.2.401
mono: none

branches:
  only:
  - master

os:
  - linux
  - osx

osx_image: xcode9.1
before-script:

script:
 - export PATH="$PATH:$HOME/.dotnet/tools"
 - dotnet tool install --global FlubuCore.GlobalTool --version 4.2.7
 - flubu Rebuild.Server -apiKey=${Nuget_Api_Key}
