language: csharp
solution: Natasha.sln
mono: none
dotnet: 2.2
dist: xenial
sudo: required

before_install:
  - sudo apt-get install nuget
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
install:
  - dotnet restore
script:
  - dotnet build -c Release