version: 2.7.6.{build}
image:
- Visual Studio 2019




configuration: Release
clone_depth: 50

pull_requests:
  do_not_increment_build_number: true
  
branches:
  only:
    - master
#skip_branch_with_pr: true
skip_commits:
  files:
    - docs/*
    - Image/*
    - media/*
    - LICENSE
    - mkdocs.yml
    - README.md
    - .travis.yml
    - .gitignore
    - azure-pipelines.yml
    - lang/*
    - article/*

for:
-
  matrix:
    only:
      - image: Visual Studio 2019


  install:
  #- ps: cd c:\projects\xxx
                
  before_build:
  - ps: dotnet restore Natasha.sln
  - ps: choco install opencover.portable
  - ps: choco install codecov

  build_script:
  - ps: dotnet build Natasha.sln -c Release
  

  test_script:
  - ps: cd ./test/NatashaUT
  - ps: OpenCover.Console.exe -register:user -target:"dotnet.exe" -targetargs:test -output:".\coverage.xml" -oldstyle
  - ps: codecov -f "coverage.xml" -t %COVERAGE_KEY%