# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

jobs:

- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'


  steps:
  - task: DotNetCoreInstaller@0
    displayName: install
    inputs:
      version: '2.2.300'


  - task: DotNetCoreCLI@1
    displayName: restore
    inputs:
      command: restore
      projects: './Natasha/Natasha.csproj'



  - task: DotNetCoreCLI@2
    displayName: build
    inputs:
      command: build
      projects: './Natasha/Natasha.csproj'
      arguments: '-c Release'




- job: macOS
  pool:
    vmImage: 'macOS-10.14'


  steps:
  - task: DotNetCoreInstaller@0
    displayName: install
    inputs:
      version: '2.2.300'


  - task: DotNetCoreCLI@1
    displayName: restore
    inputs:
      command: restore
      projects: './Natasha/Natasha.csproj'

  - script: ls
  - task: DotNetCoreCLI@2
    displayName: build
    inputs:
      command: build
      projects: './Natasha/Natasha.csproj'
      arguments: '-c Release'




- job: Windows
  pool:
    vmImage: 'windows-2019'


  steps:
  - task: DotNetCoreInstaller@0
    displayName: install
    inputs:
      version: '2.2.300'


  - task: DotNetCoreCLI@1
    displayName: restore
    inputs:
      command: restore
      projects: './Natasha/Natasha.csproj'


  - task: DotNetCoreCLI@2
    displayName: build
    inputs:
      command: build
      projects: './Natasha/Natasha.csproj'
      arguments: '-c Release'
