# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
    - appveyor.yml
    - .travis.yml
    - lang/*
    - article/*
    - docs/*

jobs:
    

- job: Linux_Core2
  pool:
    vmImage: 'ubuntu-16.04'

  
  steps:
  - task: DotNetCoreInstaller@0
    displayName: 'install core2'
    inputs:
      version: '2.2.401'
  - task: DotNetCoreInstaller@1
    displayName: 'install core3'
    inputs:
      version: '3.0.0-preview8'


  - task: DotNetCoreCLI@1
    displayName: restore
    inputs:
      command: restore
      projects: './src/Natasha/Natasha.csproj'


  - task: DotNetCoreCLI@1
    displayName: build
    inputs:
      command: build
      projects: './src/Natasha/Natasha.csproj'
      arguments: '-c Release'


  - task: DotNetCoreCLI@2
    displayName: test
    inputs:
      command: test




- job: macOS_Core2
  pool:
    vmImage: 'macOS-10.14'


  steps:
  - task: DotNetCoreInstaller@0
    displayName: 'install core2'
    inputs:
      version: '2.2.401'
  - task: DotNetCoreInstaller@1
    displayName: 'install core3'
    inputs:
      version: '3.0.0-preview8'


  - task: DotNetCoreCLI@1
    displayName: restore
    inputs:
      command: restore
      projects: './src/Natasha/Natasha.csproj'


  - task: DotNetCoreCLI@1
    displayName: build
    inputs:
      command: build
      projects: './src/Natasha/Natasha.csproj'
      arguments: '-c Release'


  - task: DotNetCoreCLI@2
    displayName: test
    inputs:
      command: test




- job: Windows_Core2
  pool:
    vmImage: 'windows-2019'


  steps:
  - task: DotNetCoreInstaller@0
    displayName: 'install core2'
    inputs:
      version: '2.2.401'
  - task: DotNetCoreInstaller@1
    displayName: 'install core3'
    inputs:
      version: '3.0.0-preview8'


  - task: DotNetCoreCLI@1
    displayName: restore
    inputs:
      command: restore
      projects: './src/Natasha/Natasha.csproj'


  - task: DotNetCoreCLI@1
    displayName: build
    inputs:
      command: build
      projects: './src/Natasha/Natasha.csproj'
      arguments: '-c Release'


  - task: DotNetCoreCLI@2
    displayName: test
    inputs:
      command: test